### PR TITLE
Added cd <dir> and cd .. commands to change directory.

### PR DESCRIPTION
**Pull request by scottfabini**
Added JUnit tests for mkdir, cd, and cd ..  Unable to test rmdir because speedtest.tele2.net deletes the dir immediately, so can't subsequently delete without our own ftp server.

Also incorporated my prior mkdir/rmdir pull request, starting from a fresh clone (as of 7/25), to make it easier to review/merge.

### CODE REVIEW

**Comment by galxy25** [comment]
Lots of helpful feedback here for you @scottfabini

**Comment by scottfabini** [comment]
Appreciate the feedback.  Please bear with me as I go from "You took 202 in Winter" and "You just learned about JUnit" to "You're writing actual Java code."

**Comment by galxy25** [comment]
For sure @scottfabini . This class is about agile not about Java :-)

**Comment by galxy25** [comment]
@scottfabini can you address @pault2k14 comments here and fix the merge conflicts? I can help you with the latter if you want.

**Comment by scottfabini** [comment]
I've resolved Paul's comments in the f0d86e0 pull request.  I removed the "cdParent" method and just handled the ".." case in the cd method.  My Friday is booked TA'ing 202 labs, so I'll look at the merge conflicts this weekend.

**Comment by scottfabini** [comment]
Corrected the merge conflict, which was occurring on 
commands.put("download", () -> { fileTransfer(input); });
commands.put("upload", () -> { fileTransfer(input); });

**Comment by galxy25** [comment]
LGTM @scottfabini

**Comment by pault2k14** [comment]
Scott, please uncomment your tests, adjust them to interact with the new FTP server and ensure that they pass.

**Pull request merged**
